import type { Services8Props } from "./schema";

/** Demo content for Services8 — used by the preview page + make-section script. */
export const sample: Services8Props = {
	badge: "Services",
	title: "What we do",
	subtitle: "Tell us what you need, and we'll find the right expertise to make it happen flawlessly.",
	priceLabel: "Price",
	timelineLabel: "Timeline",
	accent: "#1c1b19",
	tabs: [
		{
			label: "Kitchens",
			title: "Kitchens",
			description: "We design and build beautiful kitchens tailored to your lifestyle. From modern open-plan spaces to timeless family kitchens, our team focuses on smart storage, durable materials, and a finish that feels both elegant and practical.",
			price: "from 5 000$",
			timeline: "2 month avg.",
			features: "Custom Kitchen Design, Premium stone & natural wood, Design, build & installation, Premium finishes",
			image: "https://picsum.photos/seed/kitchen/900/800",
			alt: "Kitchen build",
		},
		{
			label: "Bathrooms",
			title: "Bathrooms",
			description: "Spa-inspired bathrooms that balance comfort and function. We handle everything from layout and plumbing to tiling and lighting for a space you'll love every day.",
			price: "from 3 500$",
			timeline: "5 week avg.",
			features: "Wet rooms, Underfloor heating, Bespoke vanities, Premium finishes",
			image: "https://picsum.photos/seed/bathroom/900/800",
			alt: "Bathroom build",
		},
		{
			label: "Loft Conversions",
			title: "Loft Conversions",
			description: "Turn unused roof space into a bright bedroom, studio or office. Structural work, insulation, stairs and finishing — handled end to end.",
			price: "from 18 000$",
			timeline: "3 month avg.",
			features: "Structural calcs, Dormer & Velux, Staircase design, Building control",
			image: "https://picsum.photos/seed/loft/900/800",
			alt: "Loft conversion",
		},
		{
			label: "Extensions",
			title: "Extensions",
			description: "Single or double-storey extensions that add space and value. We manage planning, build and finish so your home grows seamlessly.",
			price: "from 25 000$",
			timeline: "4 month avg.",
			features: "Planning support, Steel & groundwork, Glazing & roofing, Full project management",
			image: "https://picsum.photos/seed/extension/900/800",
			alt: "Home extension",
		},
		{
			label: "Restorations",
			title: "Restorations",
			description: "Careful restoration of period and heritage properties — preserving character while bringing comfort up to modern standards.",
			price: "from 12 000$",
			timeline: "3 month avg.",
			features: "Heritage materials, Plaster & cornicing, Sash windows, Conservation-grade finishes",
			image: "https://picsum.photos/seed/restore/900/800",
			alt: "Property restoration",
		},
		{
			label: "External Works",
			title: "External Works",
			description: "Driveways, patios, landscaping and rendering that lift your home's kerb appeal and durability.",
			price: "from 4 000$",
			timeline: "4 week avg.",
			features: "Driveways & patios, Rendering, Landscaping, Drainage",
			image: "https://picsum.photos/seed/external/900/800",
			alt: "External works",
		},
	],
};
